declare global {
  interface Window {
    _env_?: { REACT_APP_API_URL?: string };
  }
}

// Runtime value (from env-config.js, generated by render.yaml at build time)
// takes precedence over the CRA build-time baked value, which in turn falls
// back to localhost for local development.
export const API_URL =
  window._env_?.REACT_APP_API_URL ||
  process.env.REACT_APP_API_URL ||
  'http://localhost:8001';
