declare global {
  interface Window {
    _env_?: { REACT_APP_API_URL?: string };
  }
}

const inferDevApiUrl = (): string => {
  // CRA proxy (package.json "proxy") forwards unknown requests to the
  // backend at http://localhost:8001 inside the container.  By returning
  // an empty string we use relative URLs ("/auth/me", "/api/...") which
  // the dev-server proxies automatically — no extra port-forwarding or
  // CORS configuration is required.
  return '';
};

// Runtime value (from env-config.js, generated by render.yaml at build time)
// takes precedence over the CRA build-time baked value, which in turn falls
// back to localhost for local development.
export const API_URL =
  window._env_?.REACT_APP_API_URL ||
  process.env.REACT_APP_API_URL ||
  inferDevApiUrl();
